package:
  name: maestro
  version: "1.2.1"
source:
  path: ../../
# build:
#   entry_points:
#     - strap = strap:main
requirements:
  build:
    - xorg-libxrender
    - python =3.7
    - pip
    - numpy =1.17.3
    - scipy =1.4.1
    - h5py =2.10.0
    - pytables =3.6.1
    - setuptools
    - snakemake =5.14
    - rseqc =3.0.0
    - star =2.7.3a
    - minimap2 =2.17
    - samtools =1.9
    - bedtools =2.29.2
    - rsem =1.3.2
    - picard =2.22.0
    - macs2 =2.2.6
    - umap-learn
    - pysam # this is needed by sinto
    - r-base=3.6.3
    - r-BiocManager
    - r-devtools
    - r-hdf5r
    - r-SDMTools
    - r-optparse
    - r-stringi
    - r-latticeExtra
    - r-multcomp
    - r-numDeriv
    - r-cluster
    - r-Seurat =3.1.2
    # Although the following will be installed through the dependencies of other tools
    # They have been explicitly defined in DESCRIPTION. 
    - r-ggplot2 >=3.0.0 
    - r-ggrepel         
    - r-cowplot         
    - r-matrix
    - r-dplyr
    - r-png
    - r-rcolorbrewer
    - r-scales
    - r-pheatmap
    - r-gridbase
    - bioconductor-mageckflute
    - bioconductor-karyoploter
    # -----
    - bioconductor-multtest
    - bioconductor-biomaRt
    - bioconductor-MAST
    - bioconductor-AnnotationDbi
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-BiocGenerics
    - bioconductor-GO.db
    - bioconductor-pcaMethods
    - bioconductor-GenomicRanges
    - bioconductor-BiocGenerics
    - bioconductor-Rsamtools
    - bioconductor-chromVAR
    - bioconductor-motifmatchr
    - bioconductor-cicero
    - bioconductor-genefilter
    - bioconductor-GOSemSim
    - bioconductor-DESeq2
    - bioconductor-TxDb.Hsapiens.UCSC.hg38.knownGene
    - bioconductor-TxDb.Mmusculus.UCSC.mm10.knownGene
  run:
    - xorg-libxrender
    - python =3.7
    - numpy =1.17.3
    - scipy =1.4.1
    - h5py =2.10.0
    - pytables =3.6.1
    - setuptools
    - snakemake =5.14
    - rseqc =3.0.0
    - star =2.7.3a
    - minimap2 =2.17
    - samtools =1.9
    - bedtools =2.29.2
    - rsem =1.3.2
    - picard =2.22.0
    - macs2 =2.2.6
    - umap-learn 
    - pysam # this is needed by sinto   
    - r-base=3.6.3
    - r-BiocManager
    - r-devtools
    - r-hdf5r
    - r-SDMTools
    - r-optparse
    - r-stringi
    - r-latticeExtra
    - r-multcomp
    - r-numDeriv
    - r-cluster
    - r-Seurat =3.1.2
    # Although the following will be installed through the dependencies of other tools
    # They have been explicitly defined in DESCRIPTION. 
    - r-ggplot2 >=3.0.0 
    - r-ggrepel         
    - r-cowplot         
    - r-matrix
    - r-dplyr
    - r-png
    - r-rcolorbrewer
    - r-scales
    - r-pheatmap
    - r-gridbase
    - bioconductor-mageckflute
    - bioconductor-karyoploter
    # -----
    - bioconductor-multtest
    - bioconductor-biomaRt
    - bioconductor-MAST
    - bioconductor-AnnotationDbi
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-BiocGenerics
    - bioconductor-GO.db
    - bioconductor-pcaMethods
    - bioconductor-GenomicRanges
    - bioconductor-BiocGenerics
    - bioconductor-Rsamtools
    - bioconductor-chromVAR
    - bioconductor-motifmatchr
    - bioconductor-cicero
    - bioconductor-genefilter
    - bioconductor-GOSemSim
    - bioconductor-DESeq2
    - bioconductor-TxDb.Hsapiens.UCSC.hg38.knownGene
    - bioconductor-TxDb.Mmusculus.UCSC.mm10.knownGene

about:
  home: https://github.com/liulab-dfci/MAESTRO
  license: GPL-3.0
  summary: MAESTRO(Model-based AnalysEs of Single-cell Transcriptome and RegulOme) is a comprehensive single-cell RNA-seq and ATAC-seq analysis suit built using snakemake. 
